version: '3.7'

services:
  echo-container5000:
    build:
      context: .
    environment:
      - PORT=5000
    expose:
    - 5000

  # to test multiple upstream server blocks
  echo-container5001:
    build:
      context: .
    environment:
      - PORT=5001
    expose:
    - 5001

  nginx_load_balancer:
    container_name: lb
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - echo-container5000
      - echo-container5001
