version: '3.7'

services:
  echo-container:
    build:
      context: .
    expose:
    - 5000

  nginx_load_balancer:
    container_name: lb
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - echo-container
