version: '3.7' # TODO: upgrade to 3.8

services:
  vault:
    container_name: vault
    image: vault:1.9.0
    # build:
    #   context: ./vault
    #   dockerfile: Dockerfile
    expose:
      - "8200"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server #-config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul

  consul:
    container_name: consul
    # build:
    #   context: ./consul
    #   dockerfile: Dockerfile
    #image: consul:1.11.0-beta
    image: consul:1.10
    expose:
      - "8500" # HTTP API
      - "8300" # Server RPC
      - "8301" # LAN Serf
    # Single instance used to bootstrap as a single node, then any number of nodes can then join.
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.json
    volumes:
      - ./consul/config/consul-config.json:/consul/config/config.json

  # Scaled via "make start count=X". Ideally set to 2 for a 3 node cluster, including the bootstrap node above."
  consul-workers:
    # build:
    #   context: ./consul
    #   dockerfile: Dockerfile
    image: consul:1.10
    expose:
      - "8500" # HTTP API
      - "8300" # Server RPC
      - "8301" # LAN Serf
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -join consul -config-file=/consul/config/config.json
    volumes:
      - ./consul/config/consul-config.json:/consul/config/config.json
    depends_on:
      - consul

  nginx_loadbalancer:
    container_name: lb
    image: nginx:alpine
    ports:
      - 8500:8500
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - consul
      - consul-workers
